packages:
  - apps/*
  - packages/*

nodeLinker: hoisted

catalog:
  react: ^19.1.0
  react-dom: ^19.1.0
  "@types/react": ^19.1.0
  "@types/react-dom": ^19.1.1

onlyBuiltDependencies:
  - "@parcel/watcher"
  - "@sentry/cli"
  - "@swc/core"
  - esbuild
  - sharp
  - "*"

supportedArchitectures:
  os:
    - current
    - darwin
    - linux
  cpu:
    - current
    - x64
    - arm64
