### list bucket files

GET https://vercel-nest-gql-lms.vercel.app/files/listFilesVercelblob HTTP/1.1


### 


### get file

GET http://localhost:8002/files/getFileVercelBlob/testFolder103/test101.png HTTP/1.1


### delete file

DELETE http://localhost:8002/files/deleteFileVercelBlob/testFolder103/test101.png HTTP/1.1


### 


### make bucket public

POST http://localhost:8000/adminApi/files/makeBucketPublic/tutorial-images HTTP/1.1


### 


### upload file

POST https://vercel-nest-gql-lms.vercel.app/files/uploadFileVercelBlob HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary
Authorization: Bearer {{admin_token}}

------WebKitFormBoundary
Content-Disposition: form-data; name="folderName"

testFolder103

------WebKitFormBoundary
Content-Disposition: form-data; name="fileName"

test102.png

------WebKitFormBoundary
Content-Disposition: form-data; name="file"; filename="sample3.png"
Content-Type: image/png

< ~/Pictures/colors.jpg

------WebKitFormBoundary--


### 
