### 

POST https://root-lms-api.vercel.app/payment/create-checkout-session HTTP/1.1
Content-Type: application/json

{
  "lookupKey": "plus",
  "userId": "42af69ef-d158-4681-ac33-71ec6ab9aef4"
}

POST https://root-lms-api.vercel.app/payment/webhook HTTP/1.1
