import '@repo/ui/styles.css';
import '@repo/mdxSetup/styles.css';


import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";
import AdminLayout from "./layout/MainLayout";
import { TanstackProvider } from "@repo/gql";
import { DashboardStoreProvider } from "@repo/reduxSetup";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning >
      <body
      >
        <ThemeProvider attribute="class" defaultTheme="dark">

          <DashboardStoreProvider>

            <TanstackProvider>

              <AdminLayout>

                {children}

              </AdminLayout>

            </TanstackProvider>

          </DashboardStoreProvider>

        </ThemeProvider>

      </body>
    </html>
  );
}
